[2024-04-20T15:50:47.878+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-04-20T15:50:46.264078+00:00 [queued]>
[2024-04-20T15:50:47.890+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-04-20T15:50:46.264078+00:00 [queued]>
[2024-04-20T15:50:47.890+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-04-20T15:50:47.904+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2024-04-20 15:50:46.264078+00:00
[2024-04-20T15:50:47.910+0000] {standard_task_runner.py:57} INFO - Started process 50 to run task
[2024-04-20T15:50:47.913+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extraction', 'manual__2024-04-20T15:50:46.264078+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmptfrxarqt']
[2024-04-20T15:50:47.915+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask reddit_extraction
[2024-04-20T15:50:47.967+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-04-20T15:50:46.264078+00:00 [running]> on host a5ce8015e481
[2024-04-20T15:50:48.277+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Tawfik Yasser' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-04-20T15:50:46.264078+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-20T15:50:46.264078+00:00'
[2024-04-20T15:50:48.280+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 27, in reddit_pipeline
    transformed_data = transform_posts(file_name)
  File "/opt/airflow/etls/reddit_etl.py", line 44, in transform_posts
    df = pd.read_csv(file_name)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/data/input/reddit_posts.csv'
[2024-04-20T15:50:48.293+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extraction, execution_date=20240420T155046, start_date=20240420T155047, end_date=20240420T155048
[2024-04-20T15:50:48.310+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task reddit_extraction ([Errno 2] No such file or directory: '/data/input/reddit_posts.csv'; 50)
[2024-04-20T15:50:48.329+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-04-20T15:50:48.355+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
